### ISSUE TITLE
Can't Seem to pull nodes or Drive data from Element OS 10.1

### ISSUE THREAD

**Issue by supertech4321** [jedimt/sfcollector#1]
Have the latest version of Element OS, when dashboard loads nodes and drives data does not show up.

**Comment by supertech4321** [comment]
Found a bug. Collector did not seem to fully load all data into graphite. Had to comment out the below line to have it send volume data into graphite for grafana to graph. Something in the Node section of the collector is not being defined... Need some help with this. 

#    send_node_stats(sfe, cluster_name + '.node')

**Comment by jedimt** [comment]
I've verified the collector works on latest Element OS 10.1 (as well as upcoming 10.2) releases. I'm cleaning up some stuff in the repository today. Pull the latest bits and give it a shot.
