### ISSUE TITLE
bootstrap.sh uses relative path to basic_auth

### ISSUE THREAD

**Issue by scaleoutsean** [jedimt/sfcollector#3]
The PDF says "3. Run the bootstrap.sh file", which is correct, but:
```
sean@elementos:~$ sudo /opt/github/sfcollector/bootstrap.sh 
Enter a password for the graphite user
password
/opt/github/sfcollector/bootstrap.sh: line 10: ./graphiteconfig/basic_auth: No such file or directory
```
The script could be changed or a note could be added to execute the script from its directory:
```
cd /opt/github/sfcollector
./bootstrap.sh
```

**Comment by jedimt** [comment]
Sean, I'd rather leave the script using a relative path in case folks deploy it to somewhere other than /opt/github/sfcollector

That being said, I'll amend the documentation to make that more clear as you point out in your comment.
